default_language_version:
    python: python3.8
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/myint/docformatter
    rev: v1.3.1
    hooks:
    -   id: docformatter
        args: [--in-place,--wrap-summaries,"100",--wrap-descriptions,"100"]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy
        exclude: 'src/.*/competitor_code/team_\d+.py'
-   repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        stages: [push]
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
